openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
servers:
  - url: https://localhost:8080/api
tags:
  - name: homework
    description: Operations about homework
paths:
  /homeworks:
    get:
      tags:
        - homework
      summary: Get all homeworks
      description: Get all homeworks
      responses:
        '200':
          description: Successful operation
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/HomeworkList'
        '403':
          description: Forbidden request
    post:
      tags:
        - homework
      summary: Create homework
      description: Create homework
      requestBody:
        description: Create a new homework
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostHomework'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                    example: 2
                    description: 'Generated homework id'
        '400':
          description: Bad request
        '403':
          description: Forbidden request
  /homeworks/{homeworkId}:
    get:
      tags:
        - homework
      parameters:
        - name: homeworkId
          in: path
          description: ID of homework to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
          content:
            applications/json:
              schema:
                $ref: '#/components/schemas/GetHomework'
        '403':
          description: Forbidden request
        '404':
          description: Homework not found
    patch:
      tags:
        - homework
      parameters:
        - name: homeworkId
          in: path
          description: ID of homework to return
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        description: Update homework
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchHomework'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Bad request
        '403':
          description: Forbidden request
        '404':
          description: Homework not found
    delete:
      tags:
        - homework
      parameters:
        - name: homeworkId
          in: path
          description: ID of homework to return
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Successful operation
        '403':
          description: Forbidden request
components:
  schemas:
    HomeworkList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/GetHomework'
    GetHomework:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 1
        name:
          type: string
          example: 'Основы Git'
        topic:
          type: string
          example: 'Git'
        description:
          type: string
          example: 'Описание домашки'
        departments:
          type: array
          items:
            type: string
          example:
            - 'FRONT'
            - 'BACK'
        author:
          $ref: '#/components/schemas/Author'
        lecture:
          $ref: '#/components/schemas/Lecture'
        repositoryLink:
          type: string
          example: 'https://gitlab.com/hw_git'
        startDate:
          type: string
          format: date-time
          example: '2018-03-20T00:00:00Z'
        completionDeadline:
          type: string
          format: date-time
          example: '2018-03-25T00:00:00Z'
        reviewDuraion:
          type: integer
          format: int32
          example: 48
    PostHomework:
      type: object
      required:
        - 'name'
        - 'topic'
        - 'authorId'
        - 'lectureId'
        - 'startDate'
        - 'completionDeadline'
        - 'reviewDuraion'
      properties:
        name:
          type: string
          example: 'Основы Git'
        topic:
          type: string
          example: 'Git'
        description:
          type: string
          example: 'Описание домашки'
        authorId:
          type: integer
          format: int32
          example: 2
        lectureId:
          type: integer
          format: int32
          example: 3
        repositoryLink:
          type: string
          example: 'https://gitlab.com/hw_git'
        startDate:
          type: string
          format: date-time
          example: '2018-03-20T00:00:00Z'
        completionDeadline:
          type: string
          format: date-time
          example: '2018-03-25T00:00:00Z'
        reviewDuraion:
          type: integer
          format: int32
          example: 48
    PatchHomework:
      type: object
      required:
        - 'authorId'
      properties:
        name:
          type: string
          example: 'Основы Git'
        topic:
          type: string
          example: 'Git'
        description:
          type: string
          example: 'Описание домашки'
        repositoryLink:
          type: string
          example: 'https://gitlab.com/hw_git'
        startDate:
          type: string
          format: date-time
          example: '2018-03-20T00:00:00Z'
        completionDeadline:
          type: string
          format: date-time
          example: '2018-03-25T00:00:00Z'
        reviewDuraion:
          type: integer
          format: int32
          example: 48
    Author:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 2
        firstName:
          type: string
          example: 'Иван'
        lastName:
          type: string
          example: 'Иванов'
    Lecture:
      type: object
      properties:
        id:
          type: integer
          format: int32
          example: 3
        name:
          type: string
          example: 'Лекция по Git'
