spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5433/cross_review
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
server:
  port: 8080
  servlet.context-path: /
jwt:
  secret:
    access: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
    refresh: 984hg493gh0s5f46sd54f21sdfsda9yh937gc763fe87t3f89723gf
  lifetime:
    access: 1d
    refresh: 30d
springdoc:
  swagger-ui:
    url: /api/openapi.json
