spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cross_review
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
server:
  port: 8080
  servlet.context-path: /
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 300m
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    config-url: /api/openapi.json
    url: /api/openapi.json
    path: /swagger-ui.html
  api-docs:
    path: /api/openapi.json
