spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cross_review
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
server:
  port: 8080
  servlet.context-path: /
