
name: cross_review_workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push frontend to Docker Hub web
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: semashkevichea/cross_review_front:latest
          context: cross_review_front
          file: frontend/dockerfile
      - name: Push backend to Docker Hub web
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: semashkevichea/cross_review_back:latest
          context: cross_review_back
          file: backend/Dockerfile

  deploy:
    if: ${{ github.ref }} == 'main'
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: ./docker-compose.yml
          target: ./
          script: |
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker-compose pull          
            sudo rm .env
            touch .env
            echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
            echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
            echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env
            sudo docker-compose up -d         
  
